export const dataQ = [
    {
        id: 1,
        question: '¿Aceptarías trabajar escribiendo en la sección económica de un diario?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 2,
        question: '¿Te ofrecerías para organizar la despedida de uno de tus amigos?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 3,
        question: '¿Te gustaría dirigir un proyecto de urbanización en tu provincia?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 4,
        question: 'A una frustración ¿opones un pensamiento positivo?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 5,
        question: '¿Te dedicarías a socorrer a personas accidentadas o atacadas por asaltantes?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 6,
        question: 'Cuando eras niño/a ¿Te interesaba saber cómo estaban construidos tus juguetes?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 7,
        question: '¿Te interesan más los misterios de la naturaleza que los secretos de la tecnología?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 8,
        question: '¿Escuchas atentamente los problemas que te plantean tus amigos?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 9,
        question: '¿Te ofrecerías para explicar a tus compañeros un tema que ellos no entendieron?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 10,
        question: '¿Eres exigente y crítico con tu equipo de trabajo?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 11,
        question: '¿Te atrae armar rompecabezas?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 12,
        question: '¿Puedes establecer la diferencia conceptual entre macroeconomía ymicroeconomía?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 13,
        question: 'Usar uniforme ¿te hace sentir importante y distinto?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 14,
        question: '¿Participarías como profesional en un espectáculo de acrobacia aérea?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 15,
        question: '¿Organizas tu dinero de forma tal que te alcances hasta el próximo cobro?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 16,
        question: '¿Convences fácilmente a las otras personas de la validez de tus argumentos?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 17,
        question: '¿Estás informado sobre los nuevos descubrimientos de la teoría del Bing-Bang?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 18,
        question: 'Ante una situación de emergencia ¿actúas rápidamente?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 19,
        question: 'Cuando hay que resolver un problema matemático ¿perseveras hasta llegar a lasolución?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 20,
        question: 'Si te convoca tu club preferido para planificar, organizar y dirigir un campo de deportes ¿aceptarías?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 21,
        question: '¿Eres el que pone un toque de alegría en las fiestas?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 22,
        question: '¿Crees que los detalles son tan importantes como el todo?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 23,
        question: '¿Te sentirías a gusto trabajando en un ámbito hospitalario?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 24,
        question: '¿Te gustaría participar para mantener el orden ante grandes desastres naturales?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 25,
        question: '¿Pasarías varias horas leyendo algún libro de tu interés?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 26,
        question: '¿Planificas detalladamente tus trabajos antes de empezar?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 27,
        question: '¿Entablas una relación casi personal con tu computadora?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 28,
        question: '¿Disfrutas modelando con arcilla?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 29,
        question: '¿Ayudarías a un no vidente a cruzar la calle?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 30,
        question: '¿Consideras importante que desde la escuela se fomente la actitud crítica y la participación activa?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 31,
        question: '¿Aceptarías que las mujeres formaran parte de las fuerzas armadas bajo las mismas normas que los hombres?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 32,
        question: '¿Te gustaría crear nuevas técnicas para descubrir patologías de algunas enfermedades a través del microscopio?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 33,
        question: '¿Participarías en una campaña de prevención contra el mal de Chagas?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 34,
        question: '¿Te interesan los temas relacionados al pasado y a la evolución del hombre?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 35,
        question: '¿Te incluirías en un proyecto de investigación de los movimientos sísmicos y sus consecuencias?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 36,
        question: 'Fuera de los horarios escolares ¿dedicas algún día de la semana a la realización de actividades corporales?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 37,
        question: '¿Te interesan actividades de mucha acción y de reacción rápida en situaciones imprevistas y de peligro?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 38,
        question: '¿Te ofrecerías para trabajar como voluntario en los gabinetes espaciales de la NASA?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 39,
        question: '¿Te gusta más el trabajo manual que el intelectual?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 40,
        question: '¿Estarías dispuesto a renunciar a un momento placentero para ofrecer tu servicio como profesional?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 41,
        question: '¿Participarías de una investigación sobre violencia en el fútbol?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 42,
        question: '¿Te gustaría trabajar en un laboratorio mientras estudias?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 43,
        question: '¿Arriesgarías tu vida para salvar la vida de otro que noconoces?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 44,
        question: '¿Te agradaría hacer un curso de primeros auxilios?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 45,
        question: '¿Tolerarías empezar tantas veces como fuera necesario para obtener el logro deseado?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 46,
        question: '¿Distribuyes tus horarios del día adecuadamente para poder hacer todo lo planeado?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 47,
        question: '¿Harías un curso para aprender a fabricar instrumentos y/o piezas de las máquinas o aparatos con los que trabajas?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 48,
        question: '¿Elegirías una profesión en la que tuvieras que estar algunos meses alejado de tu familia, como por ejemplo lo hace el marino?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 49,
        question: '¿Te radicarías en una zona agrícola-ganadera para desarrollar actividades como profesional?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 50,
        question: 'Cuando estás en un grupo trabajando ¿ te entusiasma producir ideas originales y que sean tenidas en cuenta?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 51,
        question: '¿Te resulta fácil coordinar un grupo de trabajo?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 52,
        question: '¿Te resultó interesante el estudio de las ciencias biológicas?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 53,
        question: ' Si una gran empresa solicita un profesional como gerente de comercialización ¿te sentirías a gusto desempeñando ese rol?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 54,
        question: '¿Te incluirías en un proyecto nacional de desarrollo de la principal fuente de recursos de tu provincia?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 55,
        question: '¿Tienes interés por saber cuáles son las causas que determinan ciertos fenómenos, aunque saberlo no altere tu vida?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 56,
        question: '¿Descubriste algún filósofo o escritor que haya expresado tus ideas con antelación?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 57,
        question: '¿Desearías que te regalen algún instrumento musical para tu cumpleaños?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 58,
        question: '¿Aceptarías colaborar con el cumplimiento de normas en lugares públicos?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 59,
        question: '¿Crees que tus ideas son importantes y haces todo lo posible en ponerlas enpráctica?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 60,
        question: 'Cuando se descompone algún artefacto en tu casa ¿te dispones prontamente a repararlo?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 61,
        question: '¿Formarías parte de un equipo de trabajo orientado a la preservación de la flora y fauna en extinción?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 62,
        question: '¿Acostumbras a leer revistas con los últimos avances científico-tecnológico?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 63,
        question: 'Preservar las raíces culturales de nuestro país ¿te parece importante y necesario?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 64,
        question: '¿Te gustaría realizar una investigación que contribuyera a la distribución más justa de la riqueza?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 65,
        question: '¿Te gustaría realizar tareas auxiliares en una nave, como por ejemplo izado y arriado de velas, pintura y conservación del casco, arreglo de averías, conservación de motores, etc.?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 66,
        question: '¿Crees que un país debe poseer la más alta tecnología armamentista a cualquierprecio?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 67,
        question: '¿La libertad y la justicia son valores fundamentales en tu vida?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 68,
        question: '¿Aceptarías una práctica rentada en una industria de productos alimenticios en el sector de control de calidad?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 69,
        question: '¿Consideras que la salud debe ser prioritaria, gratuita y eficiente para todos?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 70,
        question: '¿Te interesaría investigar sobre alguna vacuna nueva?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 71,
        question: 'En un equipo de trabajo ¿prefieres el rol de coordinador?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 72,
        question: 'En una discusión de amigos ¿te ofreces de mediador?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 73,
        question: '¿Estás de acuerdo con la formación de un equipo de soldados profesionales?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 74,
        question: '¿Lucharías por una causa justa hasta sus últimas consecuencias?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 75,
        question: '¿Te gustaría investigar científicamente sobre cultivos agrícolas?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 76,
        question: '¿Harías un nuevo diseño de una prenda pasada de moda ente una reunión imprevista?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 77,
        question: '¿Visitarías un observatorio astronómico para conocer el funcionamiento de los aparatos?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 78,
        question: '¿Dirigirías el área de importación-exportación de una empresa?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 79,
        question: '¿Te inhibes al entrar a un lugar nuevo con gente desconocida?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 80,
        question: '¿Te gratificaría trabajar con niños?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 81,
        question: '¿Harías el diseño de un afiche para una campaña contra el SIDA?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 82,
        question: '¿Dirigirías un grupo de teatro independiente?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 83,
        question: '¿Enviarías tu currículum a una empresa automotriz que solicita gente para su área de producción?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 84,
        question: '¿Participarías de un grupo de defensa internacional dentro de una fuerza armada?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 85,
        question: '¿Te costearías tus estudios trabajando en un estudio contable?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 86,
        question: '¿Eres de los que defiende causas perdidas?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 87,
        question: 'Ante una emergencia epidémica ¿participarías en una campaña brindando tu ayuda?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 88,
        question: '¿Sabrías responder qué es ADN y ARN?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 89,
        question: '¿Elegirías una carrera cuyo instrumento de trabajo fuera la utilización de un idioma extranjero?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 90,
        question: 'Trabajar con objetos ¿te resulta más gratificante que trabajar con personas?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 91,
        question: '¿Te resultaría gratificante ser asesor contable en una empresa reconocida?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 92,
        question: 'Ante un llamado solidario ¿te ofrecerías para cuidar un enfermo?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 93,
        question: '¿Te atrae investigar los misterios del universo, por ejemplo los agujeros negros?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 94,
        question: '¿El trabajo individual te resulta más rápido y efectivo que el trabajo grupal?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 95,
        question: '¿Dedicarías parte de tu tiempo a ayudar a personas de zonas carenciadas?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 96,
        question: 'Cuando eliges tu ropa o decoras un ambiente ¿tienes en cuenta la combinación de colores, las telas o el estilo de los muebles?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 97,
        question: '¿Te gustaría trabajar como profesional dirigiendo la construcción de una empresa hidroeléctrica?',
        answer1: 'Si',
        answer2: 'No',
    },
    {
        id: 98,
        question: '¿Sabes qué es el PIB?',
        answer1: 'Si',
        answer2: 'No',
    }
]